name: R Package CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: my-r-package-ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run devtools::check()
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e 'devtools::check("/workdir", error_on = "warning")'

  coverage:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: my-r-package-ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Calculate coverage
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e 'cov <- covr::package_coverage("/workdir"); cat(round(covr::percent_coverage(cov), 1))' > coverage.txt
      
      - name: Show coverage
        run: cat coverage.txt

      - name: Create badge
        run: |
          COVERAGE=$(cat coverage.txt)
          mkdir -p .github/badges
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='100' height='20'>
                  <rect width='100' height='20' fill='#555'/>
                  <rect x='50' width='50' height='20' fill='#4c1'/>
                  <text x='25' y='14' fill='#fff' font-family='Verdana' font-size='11'>coverage</text>
                  <text x='75' y='14' fill='#fff' font-family='Verdana' font-size='11'>$COVERAGE%</text>
                </svg>" > .github/badges/coverage.svg

      - name: Commit badge if on main
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/badges/coverage.svg
          git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
          git push

