name: Check and Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: my-r-package-ci

      - name: Run devtools::check inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e "devtools::check('/workdir')"

  coverage:
    needs: check
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate coverage inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e "cov <- covr::package_coverage('/workdir'); cat(round(covr::percent_coverage(cov), 1))" > coverage.txt

      - name: Print coverage.txt contents
        run: |
          echo "Coverage percentage from coverage.txt:"
          cat coverage.txt

      - name: Generate SVG badge manually
        run: |
          COVERAGE=$(cat coverage.txt)
          mkdir -p .github/badges
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='100' height='20'>
          <rect width='100' height='20' fill='#555'/>
          <rect x='50' width='50' height='20' fill='#4c1'/>
          <text x='25' y='14' fill='#fff' font-family='Verdana' font-size='11'>coverage</text>
          <text x='75' y='14' fill='#fff' font-family='Verdana' font-size='11'>${COVERAGE}%</text>
          </svg>" > .github/badges/coverage.svg

      - name: Commit and push badge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch
          git checkout main
          git add .github/badges/coverage.svg
          git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
          git push

