name: R Package Check

on:
  push:
    branches:
      - main
      - pipeline
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: my-r-package-ci
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Replace old cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Install R package dependencies
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools"); devtools::install_deps("/workdir", dependencies = TRUE)'

      - name: Load package with devtools::load_all()
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e 'devtools::load_all("/workdir")'

      - name: Check package with devtools::check()
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e '
            check <- devtools::check("/workdir", error_on = "warning");
            if (length(check$errors) > 0 || length(check$warnings) > 0) {
              stop("There were errors or warnings during devtools::check()")
            }
          '

      - name: Calculate test coverage
        id: coverage
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e 'cov <- covr::package_coverage("/workdir"); cat(round(covr::percent_coverage(cov), 1))' > coverage.txt

      - name: Generate Coverage Badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          coverage-summary: coverage.txt

      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: .github/badges/coverage.svg

