name: Check R Package

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (optional)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: rpkgcheck:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run devtools::check()
        run: |
          docker run --rm -v ${{ github.workspace }}:/pkg rpkgcheck:latest Rscript -e 'devtools::check("/pkg", error_on = "warning")'

      - name: Run code coverage
        run: |
          docker run --rm -v ${{ github.workspace }}:/pkg rpkgcheck:latest Rscript -e 'covr::codecov(quiet = FALSE, path = "/pkg")'

      - name: Generate and commit badge
        run: |
          mkdir -p man/figures
          docker run --rm -v ${{ github.workspace }}:/pkg rpkgcheck:latest Rscript -e '
            cov <- covr::package_coverage(path = "/pkg")
            covr::coverage_to_svg(cov, file = "/pkg/man/figures/coverage.svg")
          '

      - name: Commit coverage badge
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add man/figures/coverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push

