name: R Package Check and Coverage

on:
  push:
    branches: [ main, pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: my-r-package-ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install R dependencies (from DESCRIPTION)
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e 'devtools::install_deps("/workdir", dependencies = TRUE)'

      - name: Run devtools::load_all() check
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e 'devtools::load_all("/workdir")'

      - name: Run devtools::check() and analyze results
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e '
            result <- devtools::check("/workdir", error_on = "never")
            n_errors <- length(result$errors)
            n_warnings <- length(result$warnings)
            n_notes <- length(result$notes)
            cat(sprintf("Check result: %d errors, %d warnings, %d notes\n", n_errors, n_warnings, n_notes))
            if (n_errors > 0 || n_warnings > 0) {
              stop("❌ devtools::check() failed due to errors or warnings")
            } else {
              cat("✅ devtools::check() passed with 0 errors and 0 warnings\n")
            }
          '

      - name: Run coverage analysis and save badge
        run: |
          docker run --rm -v ${{ github.workspace }}:/workdir my-r-package-ci \
          Rscript -e '
            library(covr)
            cov <- package_coverage("/workdir")
            percent <- round(percent_coverage(cov), 1)
            cat(sprintf("Coverage: %.1f%%\n", percent))
            dir.create("/workdir/man/figures", showWarnings = FALSE)
            badge <- covr::create_badge(percent, color = if (percent >= 90) "brightgreen" else if (percent >= 75) "yellow" else "red")
            writeLines(badge, "/workdir/man/figures/coverage.svg")
          '

      - name: Upload coverage badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: man/figures/coverage.svg

